language: ruby
before_install:
  - wget https://raw.githubusercontent.com/yast/yast-devtools/master/travis-tools/travis_setup.sh
  # install aspell headers and the English dictionary needeed for the check:spelling task
  - sh ./travis_setup.sh -p "yast2-devtools libaspell-dev aspell-en"
  - rm ./travis_setup.sh
script:
  - bundle exec rake check:spelling
  - bundle exec rubocop
  - bundle exec rake package
  - bundle exec gem install --local package/yast-rake*.gem
