language: ruby
before_install:
  # install aspell headers and the English dictionary
  - sudo apt-get install --no-install-recommends libaspell-dev aspell-en
script:
  - bundle exec rake test:unit
  - bundle exec rake check:spelling
  - bundle exec rake tarball
  - bundle exec gem install --local package/yast-rake*.gem
